---
name: Erlang CI

"on": [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        otp: ['24', '25', '26']
        rebar: ['3.22']

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar}}
      - name: Restore _build
        uses: actions/cache@v3
        with:
          path: _build
          key: _build-cache-for-os-${{runner.os}}-otp-${{steps.setup-beam.outputs.otp-version}}-rebar3-${{steps.setup-beam.outputs.rebar3-version}}-hash-${{hashFiles('rebar.lock')}}
      - name: Restore rebar3's cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/rebar3
          key: rebar3-cache-for-os-${{runner.os}}-otp-${{steps.setup-beam.outputs.otp-version}}-rebar3-${{steps.setup-beam.outputs.rebar3-version}}-hash-${{hashFiles('rebar.lock')}}
      - name: Compile
        run: ERL_FLAGS="-enable-feature all" rebar3 compile
      - name: Format check
        run: ERL_FLAGS="-enable-feature all" rebar3 format --verify
      - name: Run tests and verifications (features not enabled)
        run: rebar3 test
      - name: Run tests and verifications (features enabled)
        run: ERL_FLAGS="-enable-feature all" rebar3 test
